language: ruby
rvm: 2.0.0
cache: bundler
script:
- bundle exec rake
- bundle exec rubocop
- bundle exec brakeman
before_deploy:
- 
deploy:
  provider: heroku
  api_key:
    secure: ZNnGRJIwsB7Bwv5MhKaxCRsVD66Nvw+UcvrXKrUEnsYe7rGjulBxMUk6J6iXKGgc+MMjmcCxgDriTRCoVifEbFjHQTim7woXozZC9Lr742f3vg3/z4KCYQcPQTEYhpJtCnQiDvqmpHskzpB9mmDiJxl+Le17NMxOi6j1td7Bvc4=
  app: financeplanner
  on:
    repo: badmanski/finance
env:
  global:
  - secure: lFTZl+C3Sca1nXKv4SAdkCIZp3u3zTGW2JJ09zupG0aI4/2Nkr1JoTCm3ycJsV7vbrOml0at/8rVCgogrn1d+tD9XoKqAcKxq4fj0j92I1BXETAYMLwBcwKzG9lzz9ON2Wq1jK0nS3QgXWkjjqIwRoW/k2zk9M2FLbNWDRGeC1M=
  - secure: niNToMBfEcjlUO9BZahnoivmabdwHiqfHb7Ives18Luwq6FgWwAFiKcq1iIBnYfTnjAzYJwOSpM5JfLG5P4f68gZbC/JnCSQ6uwYgX78BQ0O2HA1EjQYauJbijDFJU23/yi5ebYNBN7drEKEDRbptnHti7a5ha/3f61GKZ/KM04=
  - secure: mE8yeRGQRmCsUeGaD8XKqOohBtBEijeZuR+dEfGIHTDAwOoV76fup2LIhL8afikejpRg6IdRIPKog16RaDwRl7+nMrBBJuQ+0UYPcmztgeQkqNcQ27/wce/i1AFL3ZjGk8O9MNIOr0wdLVdUUSumPy+QhL6QX4hpKKEboJUtsOE=
  - secure: FBc6/ZgwVw2ctGfgohHQnkpQf4RRcv7QK1kKSAlZoWS9v4LrNNvQyGfCNWNQxDNYklu9w/p5+m4xUq9MHIOtbUgCX1/b32X3oV124MqIYP7TjaoY+7HPHgmQ95T6RQeQ8ero4wyb6dqY7GGBwE6muX5aiVdwmyFf396BF87Hn8E=
  - secure: JlDrqd7ECkPLhuHe3gz/xPHVCbfiHIqQFCAl2dbujJqEG4CjXTs5WWFORxy1mqY71Lid18TTDmRSZaV4XXq5aews63ClG8lYtbhpE2mOeoYtpFdQDWNZjqkDe1c/Jn9BKs6Jd3xQQIK2r5GAAPb+YgnOCY303wixiLPVDiWs/WE=
