development: &generic
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 10
  database: finance_development
  schema_search_path: finance

test: &test
  <<: *generic
  database: finance_test
  schema_search_path: public
  min_messages: warning

staging: &staging
  <<: *generic
  database: <%= ENV['FINANCE_DBNAME'] %>
  username: <%= ENV['FINANCE_DBUSER'] %>
  password: <%= ENV['FINANCE_DBPASS'] %>

production:
  <<: *staging
